# python Lists, numpy.arrays and operations with those

# LISTS

In [1]:
list1=[1,2,3]
print(list1)
print(list1[0])
print(list1[1])
print(list1[2])
print(list1+list1) #list addition = concatenation
#print(list1*list1) #no such thing as list multiplication
print(2.5*list1[0])
print(2.5*list1[1])
print(2.5*list1[2])
# print(2.5*list1) #No automatic broadcasting of multiplication of scalar throughout elements in a list

[1, 2, 3]
1
2
3
[1, 2, 3, 1, 2, 3]
2.5
5.0
7.5


# NumPy ARRAYS

In [2]:
import numpy as np
array1=np.array([1,2,3])
print(array1)
print(array1[0])
print(array1[1])
print(array1[2])
print(array1+array1) #element wise addition
print(2.5*array1[0])
print(2.5*array1[1])
print(2.5*array1[2])
print(2.5*array1) #automatic broadcasting of multiplication of scalar throughout elements in a list
print(array1*array1) #element wise multiplication

[1 2 3]
1
2
3
[2 4 6]
2.5
5.0
7.5
[ 2.5  5.   7.5]
[1 4 9]


# Views and Copies

In [3]:
#original array
c0=np.zeros(3)
print(c0)

#views(pointers) or copies(independently allocated memories)?
wild1=c0 #obj wild1 not previously defined
wild2=c0[:] #obj wild2 not previously defined
wild4=c0.copy() #obj wild4 not previously defined
wild3=np.zeros(3);wild3=c0 #obj wild3 defined with zeros
wild6=np.zeros(3);wild6=c0[:] #obj wild6 defined with zeros
wild5=np.zeros(3);wild5[:]=c0[:] #obj wild5 defined with zeros
wild7=np.zeros(3);wild7[:]=c0 #obj wild5 defined with zeros

print("see, if they share memory")
print(c0)
print(wild1,"share mem?=",np.may_share_memory(c0, wild1))
print(wild2,"share mem?=",np.may_share_memory(c0, wild2))
print(wild3,"share mem?=",np.may_share_memory(c0, wild3))
print(wild4,"share mem?=",np.may_share_memory(c0, wild4))
print(wild5,"share mem?=",np.may_share_memory(c0, wild5))
print(wild6,"share mem?=",np.may_share_memory(c0, wild6))
print(wild7,"share mem?=",np.may_share_memory(c0, wild7))

c0    +=0
wild1 +=1
wild2 +=2
wild3 +=3
wild4 +=5
wild5 +=7
wild6 +=11
wild7 +=13


print("see, if they shared memory, after the increment they all have the same values because the same memory was incremented several time")
print(c0, "original")
print(wild1, "pointer","share mem?=",np.may_share_memory(c0, wild1))
print(wild2, "pointer","share mem?=",np.may_share_memory(c0, wild2))
print(wild3, "pointer","share mem?=",np.may_share_memory(c0, wild3))
print(wild4, "independent","share mem?=",np.may_share_memory(c0, wild4))
print(wild5, "independent","share mem?=",np.may_share_memory(c0, wild5))
print(wild6, "pointer","share mem?=",np.may_share_memory(c0, wild6))
print(wild7, "independent","share mem?=",np.may_share_memory(c0, wild7))

c0[:]    =0
wild1[:] =1
wild2[:] =2
wild3[:] =3
wild4[:] =5
wild5[:] =7
wild6[:] =11
wild7[:] =13


print("see, if they shared memory, after the assignment to a slice they all have the same values because the same memory was incremented several time")
print(c0, "original")
print(wild1, "pointer","share mem?=",np.may_share_memory(c0, wild1))
print(wild2, "pointer","share mem?=",np.may_share_memory(c0, wild2))
print(wild3, "pointer","share mem?=",np.may_share_memory(c0, wild3))
print(wild4, "independent","share mem?=",np.may_share_memory(c0, wild4))
print(wild5, "independent","share mem?=",np.may_share_memory(c0, wild5))
print(wild6, "pointer","share mem?=",np.may_share_memory(c0, wild6))
print(wild7, "independent","share mem?=",np.may_share_memory(c0, wild7))

c0    = c0 + 0
wild1 = wild1 + 1
wild2 = wild2 + 2
wild3 = wild3 + 3
wild4 = wild4 + 5
wild5 = wild5 + 7
wild6 = wild6 + 11
wild7 = wild7 + 13

print("see this operation behaves diffrently, the right hand side creates a new object with the result of the sum, the left hand side is then a new object with that result")
print(c0, "original")
print(wild1, "not pointer anymore","share mem?=",np.may_share_memory(c0, wild1))
print(wild2, "not pointer anymore","share mem?=",np.may_share_memory(c0, wild2))
print(wild3, "not pointer anymore","share mem?=",np.may_share_memory(c0, wild3))
print(wild4, "independent","share mem?=",np.may_share_memory(c0, wild4))
print(wild5, "independent","share mem?=",np.may_share_memory(c0, wild5))
print(wild6, "not pointer anymore","share mem?=",np.may_share_memory(c0, wild6))
print(wild7, "independent","share mem?=",np.may_share_memory(c0, wild7))

[ 0.  0.  0.]
see, if they share memory
[ 0.  0.  0.]
[ 0.  0.  0.] share mem?= True
[ 0.  0.  0.] share mem?= True
[ 0.  0.  0.] share mem?= True
[ 0.  0.  0.] share mem?= False
[ 0.  0.  0.] share mem?= False
[ 0.  0.  0.] share mem?= True
[ 0.  0.  0.] share mem?= False
see, if they shared memory, after the increment they all have the same values because the same memory was incremented several time
[ 17.  17.  17.] original
[ 17.  17.  17.] pointer share mem?= True
[ 17.  17.  17.] pointer share mem?= True
[ 17.  17.  17.] pointer share mem?= True
[ 5.  5.  5.] independent share mem?= False
[ 7.  7.  7.] independent share mem?= False
[ 17.  17.  17.] pointer share mem?= True
[ 13.  13.  13.] independent share mem?= False
see, if they shared memory, after the assignment to a slice they all have the same values because the same memory was incremented several time
[ 11.  11.  11.] original
[ 11.  11.  11.] pointer share mem?= True
[ 11.  11.  11.] pointer share mem?= True
[ 11.  11.  1

# 2d arrays and matrices

In [4]:
M1=np.array([[11,12],[21,22]]) #a (m x n) 2d arry is contructed with m 1d arrays of size n
print("M1")
print(M1)
print("")
print("element of first line (0), first column (0)")
print(M1[0,0])
print(M1[:,:]) #: means slicing, a full slice is the whole array
print(M1[0,:]) # 0 for arg1 means 1st line, : for arg2 means full column
print(np.shape(M1[0,:])) #this says we got a 1d array with size 2
print(M1[0:1,:]) # 0:1 for arg1 means lines 0(inclusive) to 1(exclusive, : for arg2 means full column - the difference from this to the previous is that this preserves shape
print(np.shape(M1[0:1,:])) #this says we got a 2d array with size 1 line and 2 columns



M1
[[11 12]
 [21 22]]

element of first line (0), first column (0)
11
[[11 12]
 [21 22]]
[11 12]
(2,)
[[11 12]]
(1, 2)


# default constructors:



In [5]:
# some default constructors:
ONES=np.ones([3,3])
print(ONES)

ZEROS=np.zeros([3,3])
print(ZEROS)

Id=np.eye(3)
print(Id)


[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# Linear algebra - matrix operations

In [6]:
M2=np.array([[1,2],[3,4]])
print(M1*M2) #element wise multiplication
print(M1/M2) #element wise 
print(M1+M2) #element wise 
print(M1-M2) #element wise 

print(M1.T) #transpose

print(M1.dot(M2)) #matrix multiplication, choose your favorite, read the docs for details
print(np.matmul(M1,M2))
print(M1 @ M2)

# C = A @ B :
# C[i,j]=summation_in_k(A[i,k]*B[k,j])
#[
#  [ 11*1 + 12*3 = 47,    11*2 + 12*4 =  70],
#  [ 21*1 + 22*3 = 87,    21*2 + 22*4 = 130]
#                                            ]

[[11 24]
 [63 88]]
[[ 11.    6. ]
 [  7.    5.5]]
[[12 14]
 [24 26]]
[[10 10]
 [18 18]]
[[11 21]
 [12 22]]
[[ 47  70]
 [ 87 130]]
[[ 47  70]
 [ 87 130]]
[[ 47  70]
 [ 87 130]]


In [7]:
col1=np.array([[1],
               [2]])

lin1=np.array([[1, 2],
              ])

array1d = np.array([1,2])


print(col1) # a single-column matrix - not quite the same as as 1d array
print(lin1) # a single-line matrix - not quite the same as as 1d array


print(col1)
print(col1.T) #can be transposed
print(col1.T.T) #back and forth

print(array1d)
print(array1d.T) #cannot be transposed

print(col1[0,0]) #single column matrix has only the column 0 but two lines 0 and 1
print(col1[1,0]) #nevertheless two indexes must be present

print(array1d[0]) #array 1d has 1 dimension
print(array1d[1]) #one index identify its elements



[[1]
 [2]]
[[1 2]]
[[1]
 [2]]
[[1 2]]
[[1]
 [2]]
[1 2]
[1 2]
1
2
1
2


In [28]:
print( lin1 @ M1 ) # #matrix operation checks dimension compatibility
print( M1 @ col1 )
print( lin1 @ col1) #yields 1x1 matrix (not quite the same as scalar)
print( col1 @ lin1 )

#print( col1 @ M1 ) #these 2 are illegal
#print( M1 @ lin1 )

# broadcasting with element wise multiplication between different shaped matrices

print("lin1 * M1=")
print(lin1)
print(M1)
print(lin1 * M1) #broadcasts lin1 * first line of M1, then lin1 * second line of M1

print("col1 * M1=")
print(col1)
print(M1)
print(col1 * M1) #broadcasts col1 * first column of M1, then col1 * second column of M1

print("lin1 * col1=")
lin1[0,:]=[1,2]
col1[:,0]=[3,5]
print(lin1*col1) #the broadcast creates 1xc * lx1 creates a matrix nxm where M[ij]=lin[0,i]*col[j,0]
print(col1 @ lin1) #coincidently the same as this matmul

print("col1*lin1=")
print(col1*lin1) #the broadcasting for elementwise multiplicaiotn does not depend on order
print(lin1 @ col1) #the matmul does

# what happens with 1d arrays

v1=np.array([1,2])
M2=np.array([[3,5],[7,11]])
print(v1)
print(M2)

print("1d @ 2d and vice versa")
#in these cases, numpy assumes an "orientation" to consider the 1d array as a single line or single column matrix and make the matmul operation in the order asked
#also the result is cast back in a 1d array, not in 2d array (matrix)
#1d matmul 2d
print(v1 @ M2) #yields as if v1 was a single line matrix and puts it in a 1d shape (1d array, not quite single line matrix)
#2d matmul 1d 
print(M2 @ v1) #yields as if v1 was a single column matrix and puts it in a 1d shape (1d array, not quite single line matrix)
#1d matmul 1d
print(v1 @ v1) #assumes as if one was column and other was line and yields scalar (no quite 1d array with size 1 nor matrix with size (1,1))

#broadcasting 2d 1d
#1d*2d
print(v1 * M2) #broadcasts as if the 1d was a single line matrix
#2d*1d
print(M2 * v1) #broadcast does not depend on order
#!!!!!



[[53 56]]
[[ 93]
 [173]]
[[13]]
[[ 3  6]
 [ 5 10]]
lin1 * M1=
[[1 2]]
[[11 12]
 [21 22]]
[[11 24]
 [21 44]]
col1 * M1=
[[3]
 [5]]
[[11 12]
 [21 22]]
[[ 33  36]
 [105 110]]
lin1 * col1=
[[ 3  6]
 [ 5 10]]
[[ 3  6]
 [ 5 10]]
col1*lin1=
[[ 3  6]
 [ 5 10]]
[[13]]
[1 2]
[[ 3  5]
 [ 7 11]]
1d 2d
[17 27]
[13 29]
5
[[ 3 10]
 [ 7 22]]
[[ 3 10]
 [ 7 22]]


# The matlab like matrix class

In [37]:
A=np.matrix('[1,2;3,5]')
B=np.matrix('[7,11;13,17]')
print(A)
print(A * B) #this is matrix multipli
print(np.multiply(A,B)) #this is element wise multiplicationcation just like in matlab

[[1 2]
 [3 5]]
[[ 33  45]
 [ 86 118]]
[[ 7 22]
 [39 85]]


Note that while this matlab-like matrix class exists, we do not recommend it
see scipy docs for details:
>"Numpy provides, in addition to np.ndarray, an additional matrix type that you may see used in some existing code. Which one to use?
>
>Short answer
>
>Use arrays.
>>    They are the standard vector/matrix/tensor type of numpy. Many numpy functions return arrays, not matrices.
>>
>>    There is a clear distinction between element-wise operations and linear algebra operations.
>>
>>    You can have standard vectors or row/column vectors if you like."

# References
* see the matrix class
 https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html
* see Elementary_Matrix_Operations_In_Python
 https://www.ibm.com/developerworks/community/blogs/jfp/entry/Elementary_Matrix_Operations_In_Python?lang=en
* construct arrays with comprehensions
 http://treyhunner.com/2015/12/python-list-comprehensions-now-in-color/
* broadcasting
 https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html
